### ISSUE TITLE
Password Hashing

### ISSUE THREAD

**Issue by stephenmac7** [Pylons/pyramid_tutorials#41]
In the getting started tutorial, on the tenth page (Security), there is no password hashing. This is an absolute requirement for security and anyone who does not know this will not hash their passwords after reading the tutorial.

**Comment by stevepiercy** [comment]
This tutorial has been superseded by the official [Quick Tutorial for Pyramid](http://docs.pylonsproject.org/projects/pyramid/en/latest/quick_tutorial/index.html) which does not yet use encryption as a best practice.

But the updated tutorial [Pyramid Blogr](http://pyramid-blogr.readthedocs.org/en/latest/registration.html) uses `passlib` and has a [warning about best practices](http://pyramid-blogr.readthedocs.org/en/latest/basic_models.html?highlight=encryption#update-database-initialization-script).

I've opened an issue: https://github.com/Pylons/pyramid/issues/2204
