### ISSUE TITLE
Updates for 1.5.x

### ISSUE THREAD

**Issue by bizoid** [Pylons/pyramid_tutorials#46]
I'm a complete noob at got this running through your awesome tutorial.

Thank you.

Agreed on the 1.5.2 updates.

Need the following additional lines:

# imports
...
import mako  (can we import specific modules instead?)
...

# configuration settings
...
config.include('pyramid_mako')
...

Also noted that the following line was included in the individual explanation of what to include in tasks.py, but not the entire tasks.py file at the bottom of the tutorial.

#imports
...
from pyramid.exceptions import NotFound
...

**Comment by stevepiercy** [comment]
@bizoid do you remember which tutorial you were using? Also which file?

If you can provide that information, then I will reopen this issue. As it is, there's not enough information to take action. Thank you!
