### ISSUE TITLE
Step 8 of quick_traversal falls over with database error

### ISSUE THREAD

**Issue by agmartin** [Pylons/pyramid_tutorials#57]
In step 7, we bootstrap the sqlite database and populate it with a root object.

In step 8, when you add the sqltraversal file, that database is no longer what's expected.

initialize_db.py has to be altered and re-run.

Lines 12-17 should be:
from .sqltraversal import (
    DBSession,
    Base,
    )

from .models import Folder

And then Lines 37-39 can be changed to this:
    with transaction.manager:
        rootnode = Folder(id=1, name='root')
        DBSession.add(rootnode)

**Comment by stevepiercy** [comment]
@agmartin I fixed this issue in PR #122. There were a whole bunch of errors.
