### ISSUE TITLE
Renderer Factory in Part 6: Templating missing

### ISSUE THREAD

**Issue by snoopy21** [Pylons/pyramid_tutorials#80]
Since Pyramid 1.5.2 renderers like Chameleon aren't default anymore, so the tests fail without adding "config.include('pyramid_chameleon')" to __init__.py. In setup.py should also be added requires = [
    ...
    'pyramid_chameleon',
]

**Comment by stevepiercy** [comment]
@snoopy21 In which tutorial and specific file?

**Comment by snoopy21** [comment]
in http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/getting_started/06-template/index.html "__init__.py" needs the line "config.include('pyramid_chameleon')" and "setup.py" requires = [...
'pyramid_chameleon',
]
actually on http://docs.pylonsproject.org/projects/pyramid-tutorials/en/latest/getting_started/07-viewclasses/index.html "__init__.py" contains the line "config.include('pyramid_chameleon')"

**Comment by stevepiercy** [comment]
Duplicate of #69.

**Comment by snoopy21** [comment]
okay, didn't see that. I did a pull request https://github.com/Pylons/pyramid_tutorials/pull/83

**Comment by stevepiercy** [comment]
closed by #83
