### ISSUE TITLE
Change repo's description to either remove or update URL

### ISSUE THREAD

**Issue by stevepiercy** [Pylons/pyramid_tutorials#81]
The current description of this repo is "Tutorials for Pyramid http://docs.pylonshq.com" and it either needs the URL removed or updated (I vote removed). Only an owner can do this.

**Comment by tseaver** [comment]
I updated the URL: http://www.pylonsproject.org/

**Comment by stevepiercy** [comment]
Actually, http://docs.pylonshq.com is now http://docs.pylonsproject.org/projects/pyramid/en/latest/ Sorry, I should have been more specific.

**Comment by tseaver** [comment]
Updated.
